# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            /mgritts_
tagline:          'wildlife ecology with a hint of CS'
description:      'Wildlife ecology with a hint of computer science'

author:
  name:           'Mitchell Gritts'

paginate:         5
gems: [jekyll-paginate]

# Custom vars
version:          0.5.0
github:           https://github.com/kissmygritts

excerpt_separator: <!--more-->
