# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Mitchell Gritts
tagline:          'R and Wildlife Ecology'
description:      'A chronicle of my trials and tribulations in R and wildlife ecology.'

author:
  name:           'Mitchell Gritts'

paginate:         5
gems: [jekyll-paginate]

# Custom vars
version:          0.5.0
github:           https://github.com/kissmygritts

excerpt_separator: <!--more-->
